apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
spec:
  generators:
    - git:
        repoURL: https://github.com/on-clouds/demo.git
        revision: HEAD
        files:
          - path: 2023-07-sbg-cloud-native/gitops/**/config.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: '{{ repoURL }}'
        targetRevision: '{{ targetRevision }}'
        chart: '{{ chart }}'
        helm:
          valueFiles:
          - $values/2023-07-sbg-cloud-native/gitops/{{ path.basename }}/values.yaml
      - repoURL: https://github.com/on-clouds/demo.git
        targetRevision: HEAD
        path: 2023-07-sbg-cloud-native/gitops/{{ path.basename }}
      - repoURL: https://github.com/on-clouds/demo.git
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
