apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: app-pre-deploy-check-infra
  namespace: podtato-kubectl
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/thschue/environment-readiness-service/main/keptn/get_state.ts
    parameters:
      map:
        url: http://environment-readiness-service.environment-readiness-service.svc.cluster.local:8080/infraReadiness
        timeout: "5"
        retries: "20"
