apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: app-post-deploy-k8sgpt
  namespace: podtato-kubectl
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/on-clouds/demos/main/2023-kceu-rejekts/keptn/k8sgpt.ts
    parameters:
      map:
        url: http://k8sgpt-service.k8sgpt.svc.cluster.local:8080/analyze
        namespace: podtato-kubectl
