apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  version: "0.1.2"
  workloads:
    - name: podtato-head-left-leg
      version: 0.1.1
    - name: podtato-head-right-leg
      version: 0.1.1
    - name: podtato-head-left-arm
      version: 0.1.1
    - name: podtato-head-frontend
      version: 0.1.0
    - name: podtato-head-right-arm
      version: 0.1.1
    - name: podtato-head-hat
      version: 0.1.2
  preDeploymentTasks:
    - app-pre-deploy-check-infra
  postDeploymentTasks:
    - app-post-deploy-k8sgpt
  preDeploymentEvaluations:
    - app-pre-deploy-eval-2
