apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
---
apiVersion: v1
data:
  servicesConfig.yaml: |
    hat:       "http://podtato-head-hat:8080"
    left-leg:  "http://podtato-head-left-leg:8080"
    left-arm:  "http://podtato-head-left-arm:8080"
    right-leg: "http://podtato-head-right-leg:8080"
    right-arm: "http://podtato-head-right-arm:8080"
kind: ConfigMap
metadata:
  name: podtato-head-discovery
  namespace: podtato-kubectl
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-frontend
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: podtato-head-frontend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: podtato-head-hat
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: podtato-head-left-arm
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: podtato-head-left-leg
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: podtato-head-right-arm
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: podtato-head-right-legs
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-frontend
  namespace: podtato-kubectl
spec:
  selector:
    matchLabels:
      app: podtato-head-frontend
  template:
    metadata:
      labels:
        app: podtato-head-frontend
        app.kubernetes.io/name: podtato-head-frontend
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: frontend
    spec:
      serviceAccountName: podtato-head
      containers:
      - env:
        - name: PODTATO_COMPONENT
          value: frontend
        - name: PODTATO_STARTUP_DELAY
          value: 10s
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: SERVICES_CONFIG_FILE_PATH
          value: /config/servicesConfig.yaml
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-frontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 8Mi
          requests:
            cpu: 100m
            memory: 6Mi
        volumeMounts:
        - mountPath: /config
          name: service-discovery-map
      volumes:
      - configMap:
          name: podtato-head-discovery
        name: service-discovery-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-hat
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-hat
  template:
    metadata:
      labels:
        app: podtato-head-hat
        app.kubernetes.io/name: podtato-head-hat
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: backend
    spec:
      containers:
      - env:
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: PODTATO_COMPONENT
          value: hat
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-hat
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-arm
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-left-arm
  template:
    metadata:
      labels:
        app: podtato-head-left-arm
        app.kubernetes.io/name: podtato-head-left-arm
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: backend
    spec:
      containers:
      - env:
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: PODTATO_COMPONENT
          value: left-arm
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-left-arm
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-leg
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-left-leg
  template:
    metadata:
      labels:
        app: podtato-head-left-leg
        app.kubernetes.io/name: podtato-head-left-leg
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: backend
    spec:
      containers:
      - env:
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: PODTATO_COMPONENT
          value: left-leg
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-left-leg
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 2m
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-arm
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-right-arm
  template:
    metadata:
      labels:
        app: podtato-head-right-arm
        app.kubernetes.io/name: podtato-head-right-arm
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: backend
    spec:
      containers:
      - env:
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: PODTATO_COMPONENT
          value: right-arm
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-right-arm
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-right-leg
  namespace: podtato-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-right-leg
  template:
    metadata:
      labels:
        app: podtato-head-right-leg
        app.kubernetes.io/name: podtato-head-right-leg
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0
        role: backend
    spec:
      containers:
      - env:
        - name: PODTATO_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: PODTATO_COMPONENT
          value: right-leg
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ghcr.io/podtato-head/podtato-server:v0.3.2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: podtato-head-right-leg
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 32Mi
