apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cert-manager/cert-manager
    targetRevision: main
    path: 2023-kceu-rejekts/app/version-1
  destination:
    server: https://kubernetes.default.svc
    namespace: podtato-kubectl
  syncPolicy:
    automated:
      selfHeal: true
      prune: true