apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: pre-deployment-check-frontend
  namespace: podtato-kubectl
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/on-clouds/demos/main/2023-kceu-rejekts/keptn/http.ts
    parameters:
      map:
        url: http://podtato-head-frontend.podtato-kubectl.svc.cluster.local:8080
