apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-setup
  namespace: argocd
spec:
  destination:
    namespace: "monitoring"
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/on-clouds/demos
    targetRevision: feat/add_vdm_2023
    path: support/observability/config/prometheus/setup
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true