apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetric
metadata:
  name: available-cpus
  namespace: podtato-kubectl
spec:
  provider:
    name: prometheus
  query: "sum(kube_node_status_capacity{resource='cpu'})"
  fetchIntervalSeconds: 10
